# config_gpu.yaml
workerPoolSpecs:
    machineSpec:
        machineType: n1-standard-8
        acceleratorType: NVIDIA_V100 
        acceleratorCount: 1
    replicaCount: 1
    containerSpec:
        imageUri: gcr.io/mlops-captcha/training