
# Default configuration file for the project

defaults:
- model: model                      # Model to be used
- optimizer: Adam_opt               # Optimizer to be used

# This statement is used to define the model to be used so sweep can override it
optimizer:
  Adam_opt:
    _target_: torch.optim.Adam      # Target to be used
    lr: 1e-3                        # Learning rate


