site_name: captcha
site_author: s204431
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
  - Model: model.md
  - Train: train.md
  - Evaluate: evaluate.md
  - Dataset: dataset.md
  - Data: data.md
  - Bentoml Service: bentoml_service.md
  - Backend Monitoring: backend_monitoring.md
  - Utils: utils.md
