name: Data Statistics Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'data/**/*.dvc'
      - '.dvc/**'

jobs:
  dataset_statistics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Pull data
        run: |
          dvc pull --no-run-cache

      - name: Check data statistics & generate report
        run: |
          # Create markdown report header
          echo "# CAPTCHA Dataset Statistics Report" > data_statistics.md
          echo "## Dataset Information" >> data_statistics.md
          echo '```' >> data_statistics.md
          
          # Run statistics script and capture output
          statistics >> data_statistics.md
          
          echo '```' >> data_statistics.md
          
          # Append visualizations
          echo "" >> data_statistics.md
          echo "## Dataset Visualizations" >> data_statistics.md
          echo "" >> data_statistics.md
          echo "### Sample CAPTCHA Images" >> data_statistics.md
          echo "![](./captcha_images.png)" >> data_statistics.md
          echo "" >> data_statistics.md
          echo "### Label Distributions" >> data_statistics.md
          echo "![](./train_label_distribution.png)" >> data_statistics.md
          echo "![](./val_label_distribution.png)" >> data_statistics.md
          echo "![](./test_label_distribution.png)" >> data_statistics.md

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Comment on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create data_statistics.md --watermark-title="CAPTCHA Data Statistics"