name: Data Statistics Check

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'data/**/*.dvc'
      - '.dvc/**'
      - 'data/'
  pull_request_target:
    branches: [ main ]
    paths:
      - 'data/**/*.dvc'
      - '.dvc/**'
      - 'data/'


jobs:
  dataset_statistics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip list 
          make dev_requirements

      - name: Auth with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Pull data
        run: |
          dvc pull --no-run-cache

      - name: Check data statistics
        run: |
          python scr/captcha/dataset.py

      - name: Check data statistics & generate report
        run: |
          # Run your dataset_statistics.py (or main.py) 
          # and capture its console output into a markdown file
          python dataset_statistics.py > report.md

          # Append inline images to the markdown file 
          # (be sure these PNGs match what your script generates)
          echo '' >> report.md
          echo '![CAPTCHA images](./captcha_images.png "CAPTCHA images")' >> report.md
          echo '' >> report.md
          echo '![Train label distribution](./train_label_distribution.png "Train label distribution")' >> report.md
          echo '' >> report.md
          echo '![Val label distribution](./val_label_distribution.png "Val label distribution")' >> report.md
          echo '' >> report.md
          echo '![Test label distribution](./test_label_distribution.png "Test label distribution")' >> report.md

      - name: Setup CML
        uses: iterative/setup-cml@v2

      - name: Comment on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create data_statistics.md --watermark-title="Data Checker" # (1)!